### ISSUE TITLE
Failed to verify game

### ISSUE THREAD

**Issue by powof2** [game-fuse/game-fuse-unity-example#1]
Hi,

When i hit play button it says : `Request had error: Failed to verify game`,

game is already created on gamefuse web site and run with assigned Id and Token.

Please help.

**Comment by game-fuse** [comment]
Hello! We have many users using it successfully and i have just tested it myself successfully?  Can you send your code to support@gamefuse.co and we can take it from there?

Thanks
Mitch
GameFuse Support

**Comment by powof2** [comment]
Hi Mitch, 
Actually i was trying to use UnityWebRequest to do some tests, because i am new to database/web programming, and i found https://resttesttest.com, its good for beginners, i'll get back here when i am ready, thank you.
